## Dockerfile for building development image
FROM mysql:5.6
LABEL maintainer "Igor Pellegrini <igor.pellegrini@live.com>"

ENV DISABLE_WELCOME_MESSAGE=1

USER root

RUN apt-get -q update \
    && apt-get -q --yes install netcat  \
    && apt-get clean

RUN chown -R mysql:mysql /var/lib/mysql

COPY --chown=mysql:mysql ./db/app-schema.sql /schemas/app-schema.sql
COPY --chown=mysql:mysql ./docker/bash_functions.sh /scripts/bash_functions.sh
# initialize project SQL files when running container (schema, migrations)
# MySql image supports docker-entrypoint-initdb.d/ to load *.sql
COPY --chown=mysql:mysql ./docker/init-from-DB_NAMES.sh /docker-entrypoint-initdb.d/init-from-DB_NAMES.sh

USER mysql

# CMD ["--user=root","--explicit_defaults_for_timestamp"]