## Dockerfile for building development image
FROM bitnami/mariadb:10.3-debian-10
LABEL maintainer "Igor Pellegrini <igor.pellegrini@live.com>"

ENV NODE_ENV=development

USER root
COPY ./db/odiometro.sql /usr/local/bin/docker-entrypoint-initdb.d/
RUN chmod -R +x /usr/local/bin/docker-entrypoint-initdb.d

# EXPOSE 3000
# CMD ["npm", "start"]
