## Dockerfile for building development image
#
# TODO:
# - use alpine mariadb; drop bitnami (implement own `waitDb`, `initDb` scripts)
# - init db manually, without needing to mount volume from docker-compose
FROM bitnami/mariadb:10.1-debian-10
LABEL maintainer "Igor Pellegrini <igor.pellegrini@live.com>"

ENV DISABLE_WELCOME_MESSAGE=1
ENV NODE_ENV=development
# ENV ALLOW_EMPTY_PASSWORD=0 # on production env

USER root
