## Dockerfile for building development image
FROM bitnami/mariadb:10.3-debian-10
LABEL maintainer "Igor Pellegrini <igor.pellegrini@live.com>"

ENV DISABLE_WELCOME_MESSAGE=1

ENV NODE_ENV=development

# ALLOW_EMPTY_PASSWORD=0 # on production env

USER root

# initialize project SQL files when running container (schema, migrations)
COPY db /docker-entrypoint-initdb.d
RUN chmod -R +x /docker-entrypoint-initdb.d
