## Dockerfile for building development image
FROM bitnami/express:4.17.1-debian-10-r218
LABEL maintainer "Igor Pellegrini <igor.pellegrini@live.com>"

ENV DISABLE_WELCOME_MESSAGE=1

ENV NODE_ENV=development \
    PORT=3000

USER root

RUN apt-get update -y && apt-get install -y bzip2

RUN chown -R 1000:1000 "/.npm"

USER bitnami

WORKDIR /app

# copy installation manifests fist (to allow caching NPM installation)
COPY --chown=bitnami:bitnami ./package.json /app/package.json
COPY --chown=bitnami:bitnami ./public/package.json /app/public/package.json
RUN npm install
RUN cd public && npm install

# copy the rest of the application code
COPY --chown=bitnami:bitnami . /app

# RUN ./app/public/node_modules/grunt/bin/grunt

# set user to run NPM scripts
USER root
RUN npm config set user bitnami

USER bitnami

EXPOSE 3000

CMD ["npm", "start"]
